### ISSUE TITLE
[spirv-io] Milestone 2 tracking

### ISSUE THREAD

**Issue by kig** [kig/spirv-wasm#18]
# Milestone 2: 80% portability

## Current state
Alpha version of the IO event loop. Tested and developed on an Nvidia RTX 2070 on Linux. GPU-only Vulkan runner, currently limited to a single GPU.

## Goals
Milestone 2 goals are to make sure that the library can be used, and is usable on 80% of devices. To achieve that, thoroughly test the IO event loop to ensure that it works (and works correctly), and port the shader runner to the CPU.

Minor goals of Milestone 2 are testing the library across a wider range of hardware (Intel iGPUs, mobiles, Windows, Mac OS), and experimenting with running the libraries on WebGPU and WASM.

## Major
- [ ] Fuller test suite coverage for the event loop
- [ ] Run the GLSL programs on the CPU

## Minor
- [ ] Test on Intel iGPU
- [ ] Test on mobile
- [ ] Test on Windows
- [ ] Test on Mac OS
- [ ] Prototypes for WASM & WebGPU
